### ISSUE TITLE
Improve loading of ReactiveStreamsFactory and ReactiveStreamsEngine to be in line with the solution in other specs

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-reactive-streams#103]
Currently, `ReactiveStreamsFactory` is loaded using service loader in a private `factory()` method. Other specs do something similar to provide an implementation (Config in [ConfigProviderResolver](https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java), REST client, etc.)

Other specs that use this pattern also do the following, which the current solution in `ReactiveStreamsFactory.factory()` does not:

* load the implementation using the thread contect classloader instead of the default classloader
* provide means to set an implementation directly and bypass service loader, this is to support environments where service loader isn't supported, mainly OSGi

An example of a solution, which meets the above 2 points, is the [ConfigProviderResolver.instance()](https://github.com/eclipse/microprofile-config/blob/1.3/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java#L102) in the Config spec.

**Comment by OndrejM** [comment]
@cescoffier @jroper, it should be enough to copy&paste from Config spec. I'd like to do it if I find time. @Emily-Jiang, maybe you could do it too, if you can find time for it sooner than me?

**Comment by cescoffier** [comment]
I don't mind using the approach from the other spec. @jroper WDYT?

**Comment by cescoffier** [comment]
BTW, the issue also affects `ReactiveStreamsEngine`.

**Comment by cescoffier** [comment]
I've updated the title to reflect the 2 cases.

**Comment by hutchig** [comment]
I have no strong opinion on this.

If you ever need to get round this problem, you might find it interesting that in WebSphere OpenLiberty (which is all OSGi)  we currently make bnd files include:

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/cnf/resources/bnd/app-resources.bnd 
after setting app-resources to the service-load file and then
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.classloading/src/com/ibm/wsspi/classloading/ResourceProvider.java
will make the resources service loadable via the Java service loading mechanism.
not saying that is an alternative solution - just for your curiosity :-).

**Comment by cescoffier** [comment]
@hutchig There are many ways to deal with SPI in OSGi environment. I tend to recommend extender patterns (at the module layer) or whiteboard patterns (at the service layer). For this issue, we should apply what the other specs have done. Allowing to pass a specific instance can also be useful in environments with limited SPI feature or reflection facilities (such as GraalVM/SubstrateVM - even if SPI support has been added recently).

**Comment by cescoffier** [comment]
@OndrejM - https://github.com/eclipse/microprofile-reactive-streams/pull/104.

**Comment by hutchig** [comment]
@cescoffier Clement, I bow to your OSGi fu...and +1 on #104.

**Comment by cescoffier** [comment]
@hutchig I love the ASCII art in the bnd file! The approach you use Declarative Services so it exposes the SPI implementation as a service. It's actually pretty nice as it does not require using `Bundle.getClassLoader()` which has security implications. 

In the PR, it just allows "any" bundle importing the package to set the instance. So, it can be used in combination with the Declarative Service approach.

**Comment by cescoffier** [comment]
PR merged in master.
