### ISSUE TITLE
Deploy releases on central

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-reactive-streams#112]
RC2 is not public, not sure the intention behind but it makes the spec not adoptable

**Comment by cescoffier** [comment]
We had a discussion on the MicroProfile mailing list about it. RCs are not public and require a bit of "config" (add the repository). Only the 1.0.0 will be GA. I don't have a strong opinion about it but it seems to be the MicroProfile process.

**Comment by jroper** [comment]
I would be more than happy to click the button to deploy to central right now, but I've been told that's not how we do things in MicroProfile. This is an issue to bring up with the rest of the MicroProfile community, perhaps at the next community hangout.

In the meantime, it can be consumed from the Sonatype staging repository, https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1126. That repo won't be around forever, Sonatype automatically drops them after a month (and this is another reason why I don't like not deploying to central), so for people that want a stable artifact location that they can rely on, I've deployed it to my own bintray repository, at https://dl.bintray.com/jroper/maven.

**Comment by rmannibucau** [comment]
Hi @jroper can you bring it to next MP meeting please?

Another question is: does the staging existence means the review process didnt happen or passed? (https://www.eclipse.org/projects/handbook/#release)

**Comment by jroper** [comment]
I raised this issue on the mailing list, and it turns out the only reason we don't publish RCs to Maven central is that no one ever asked to. So 1.0-RC2 is now published to Maven central.
