### ISSUE TITLE
Drop graph and stages

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-reactive-streams#113]
Graph and Stage are internals of an implementation, does not make much sense to let it be user facing in any way so it is probably a concept to drop from the spec just making builder not reusables for instance.

**Comment by jroper** [comment]
`Graph` and `Stage` are necessary for `ReactiveStreamsEngine` to exist, which is discussed in #114. As long as `ReactiveStreamsEngine` is needed, `Graph` and `Stage` are needed, so this is essentially the same issue as #114.

**Comment by rmannibucau** [comment]
Hmm, no?

User always starts from the builder so gets an internal representation - what you call graph but actually it is always GraphImpl - which does not need these 2 implementation details at all. Exposing it is an implementation leak.

**Comment by jroper** [comment]
The `ReactiveStreamsEngine` takes a `Graph`, which is a sequence of `Stage`'s, and turns into into a running stream. Without `Graph`, `ReactiveStreamsEngine` can't exist.

**Comment by rmannibucau** [comment]
There is no need of that in the api or said otherwise it does not bring anything. Would you expose rxjava or akka? This is exactly the same here.

Also did you intend the user to implement his own stages? Likely not cause you can break the impl this way so it means you would have to redo an engine as an user which would never be annoption IMHO.
