### ISSUE TITLE
Misuse of Engine

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-reactive-streams#114]
Engine is the equivalent of JakartaEE providers. This should only appear at the entry point of the API and not later (build) to ensure once you are bound to a provider you stay in its scope and user does not mix providers which is never expected or even testable.

**Comment by jroper** [comment]
We talked about this extensively in the Reactive meeting this week (see [minutes](https://docs.google.com/document/d/1UKBBNFn-CeMih3lNUGvpShcL2aTpnvmJs9LQ8qT9OI0/edit#).

This method actually doesn't exist to use a different provider (though it can be used to do that), it exists to allow engines configured in different ways to be used by the container.

For example, consider the following CDI bean using the messaging spec:

```java
@ApplicationScoped
public class MyBean {
  @Incoming("my-topic")
  public SubscriberBuilder<Message> handleMessages() {
    return ReactiveStreams.builder().forEach(msg -> System.out.println("I got a message: " + msg));
  }
}
```

Now, when the container uses the returned `SubscriberBuilder` to consume `my-topic`, it may want/need to run it with a particular CDI context (not currently specified by the messaging spec, but likely will be in future, there may be a dedicated stream context). By providing a `run(ReactiveStreamsEngine)` method, it can create an engine that is able to run the stream in that context, and then use it to ensure the callback passed to `forEach` always runs in that context. At least, that's the way this method and this API is intended to be used.

**Comment by rmannibucau** [comment]
Hmm, this does not work for reactive in general, and enabling to stack a context would likely more reliable cause of the thread related CDI assumption in most cases. The subscriber impl will do that - there is no other way.

Therefore it explicits that:

1. the spec misses a way to specify a provider
2. the method is not intended to be used

Side note: the example really looks like you are redoing CDI bus another way instead of leveraging it and enabling to enrich it with potential other features. This does not help adoption at all from my point of view :(.
