### ISSUE TITLE
Rename messaging spec to events spec

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams#23]
Should we rename MicroProfile Reactive Messaging to MicroProfile Reactive Events?

To be clear, this wouldn't mean that the spec doesn't deal with messages that aren't events, it can certainly still deal with that. But what it does mean is that the focus of the spec is events, with messages being a secondary concern, and it also means that it can handle events that aren't messages, such as publishing events from an event log.

One reason for doing this is to piggy back off momentum and marketing around [CloudEvents](https://cloudevents.io), and aligning with a general industry progression towards thinking about events as an important top level concept in cloud native systems.

**Comment by matzew** [comment]
Reactive-Eventing ?

**Comment by smillidge** [comment]
Only issue I can see is that CDI which is a core component of MicroProfile also has Events.

**Comment by jroper** [comment]
@smillidge This is a good point.
