### ISSUE TITLE
Stream context in messaging spec

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams#25]
We should define a CDI stream context that MicroProfile Reactive Streams implementations are required to provide, and to ensure is active during the execution of all callbacks passed to Reactive Streams builder methods, eg, to the map function executed by the `map` operator.

This could perhaps be called `@StreamScoped`. It would be worth investigating context inheritance (something that I've seen mentioned but I've never actually seen any mechanism for actually implementing it so I have no idea what it means), since it would be good if a stream context instance could inherit from the context that a given stream is attached to.

**Comment by hutchig** [comment]
I can see how this would be useful to operators/callbacks. 
There are three things that come to mind for me:

 1 - is this MVP for release 1.0 - what operators would be difficult to implement without it
and could a user provided portable CDI extension be plumbed in in any way without it being
in the spec.
2 - could this be a decoration that Microprofile adds to Streams if it is mostly there to support the implementation of operators [I need to go and grok the Stream:Messaging boundary intentions first really before documenting this concern]
3 - CDI and Contexts - So here we propose a context called StreamScope that has the lifecycle of the Stream intance built. Do we want to have the ability for an operator/callback aka 'interceptor' to be aware of, for example, [see https://docs.oracle.com/javaee/6/tutorial/doc/gmgli.html] The java.security.Principle of the 'next' Subscriber that is going to get the Message?

**Comment by jroper** [comment]
I'm thinking that perhaps, rather than having a `StreamScope`, we should require that the stream runs in the context of whatever the scope of the bean that it's defined on is. So, if the bean is defined to be `RequestScoped`, the stream should run in that scope. If it's defined to be `ApplicationScoped`, then it should run in that scope. I don't know how this could be implemented for custom scopes though, given that CDI offers no way to capture a scope and transfer it to a thread.

**Comment by jroper** [comment]
Migrated to https://github.com/eclipse/microprofile-reactive-messaging/issues/2.
