### ISSUE TITLE
Context detached streams

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams#26]
Currently the messaging spec specifies streams that are attached to the lifecycle of the context in which they run - so they are automatically started when the context is started, and automatically shut down when the context is destroyed, and kept running (restarted in case of failure) in the meantime. These streams are provided by declaring an annotated method.

There are also use cases that would require streams detached from a particular context, such as the ability to publish a single event in response to a HTTP request, as well as the ability plumb a WebSocket stream into a message broker. These streams would be provided by declaring `@Inject` annotated stream types (eg, `PublisherBuilder` and `SubscriberBuilder`), and maybe also messaging specific equivalents that offer more functionality, and the container would inject these into beans so that they can be started/stopped by the developer on demand.

**Comment by jroper** [comment]
My personal opinion for this is that we should consider it for a version 1.1, rather than 1.0.

**Comment by cescoffier** [comment]
Yes, it requires a bit more thinking. So, +1 for 1.1.

**Comment by jroper** [comment]
The concensus at the reactive weekly hangout was that it should wait till 1.1 too.

**Comment by jroper** [comment]
We should consider whether CDI Events can be used to implement this.

**Comment by jroper** [comment]
Migrated to https://github.com/eclipse/microprofile-reactive-messaging/issues/3.
