### ISSUE TITLE
Can this be integrated with CDI Events

### ISSUE THREAD

**Issue by smillidge** [eclipse/microprofile-reactive-streams#30]
Some of the annotations being produced are similar to CDI Events. Could this be used to enhance the CDI Observer model. For example Payara Micro does asynch eventing across process boundaries by adding the `@Inbound` and `@Outbound` annotations to the standard CDI apis. See https://docs.payara.fish/documentation/payara-server/public-api/cdi-events.html

**Comment by jroper** [comment]
I think it can, and @cescoffier and I were going to schedule some meetings with some of the CDI committers to discuss further.

One issue that we think exists at the moment is that listeners are unable to asynchronously propagate backpressure. Backpressure can be asynchronously propagated by event publishers using `fireAsync` and attaching to the returned `CompletionStage`. However, event listeners don't seem to have any such mechanism. One way they could provide some mechanism is by allowing them to return `CompletionStage<Void>`, and ensuring the publisher that invoked `fireAsync` doesn't have its `CompletionStage` redeemed until the listener redeems the `CompletionStage` it returns.

Other than that, we think a good way to offer integration with CDI events would be to allow them to be a messaging provider.

**Comment by hutchig** [comment]
The Payara @Inbound and @Outbound annotions have come up in some of the discussions in the hangout. CDI integration is very interesting along with an idea like 
https://simonbasle.github.io/2018/02/contextual-logging-with-reactor-context-and-mdc/
http://projectreactor.io/docs/core/release/reference/#context

**Comment by jroper** [comment]
Here's the CDI issue for backpressure on asynchronous events in CDI:

https://github.com/eclipse/microprofile-reactive/issues/30

**Comment by jroper** [comment]
Migrated to https://github.com/eclipse/microprofile-reactive-messaging/issues/4.
