### ISSUE TITLE
Messaging config

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams#43]
We need to define an approach for configuring messaging.

I'm not sure if there are any generic configuration parameters that we want to support at this stage (though perhaps being able to supply the topic name in configuration instead of in the annotation would be good), but the important thing is that we have a consistent approach for configuring things.

In some prior discussions, we've discussed adding a configuration key attribute to the annotations. The actual name of it is certainly up for date, `configKey`, `configId`, `streamId`, `id`, `key`, `config` etc are all examples.

The idea would be that if you said:

```java
@Incoming(topic = "mystream", configKey = "com.example.my-stream")
public CompletionStage<?> handleEvent(MyStreamEvent event) {
    ...
}
```

Then configuration for this stream would first be read from the `com.example.my-stream` namespace, before reading it from a general location. So for example, let's say we had a configuration parameter called `parallelism`, in the above case, we'd first read `com.example.my-stream.parallelism`, if not set there, then we might read `org.eclipse.microprofile.reactive.messaging.parallelism`, before finally defaulting to something else. We could also say that you can override the topic defined on the annotation by setting `com.example.my-stream.topic` in the configuration.

**Comment by cescoffier** [comment]
I've open an issue related to this (#70), where I propose to remove `topic` and to use a `name`. This name can be used to read the configuration as a default. But this does not avoid adding the `configKey` attribute to let the user configure the configuration key. 

Because of MP Config, the configuration is going to be given as:
```
com.example.my-stream.broker=...
com.example.my-stream.consumer-group=...
```

**Comment by jroper** [comment]
Migrated to https://github.com/eclipse/microprofile-reactive-messaging/issues/7.
