### ISSUE TITLE
Ability to create `ProcessorBuilder` from a `SubscriberBuilder` and a `PublisherBuilder`

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams#61]
It would be good to have the ability to create a `ProcessorBuilder` from a `SubscriberBuilder` and a `PublisherBuilder`.

Akka Streams provides two different methods for doing this, the first treats them as completely different streams, which is more a convenience than anything else. The second is to wrap them in a way that is "coupled", what this means is the lifecycle events - `cancel`, `onComplete` and `onError` are transferred between the `Subscriber` and the `Publisher`, so for example, if the `Subscriber` receives an `onComplete`, then the resulting `Processor` emits `onComplete`, and cancels the `Publisher`. Likewise, if the `Publisher` receives a `cancel`, then the resulting `Processor` also emits `cancel` upstream, and sends `onError(CancellationException)` to the `Subscriber`.

I think this will be useful for a number of messaging scenarios, for example, if integrating with a library that provides a `Publisher` and `Subscriber`.

**Comment by cescoffier** [comment]
+1

**Comment by hutchig** [comment]
I would suggest we could then have: 

ReactiveStreams.from( S,P ) 

as well, to keep that complete.

**Comment by cescoffier** [comment]
In `ReactiveStreams`:
```
ProcessorBuilder couple(SubscriberBuilder sub, PublisherBuilder pub);
ProcessorBuilder couple(Subscriber sub, Publisher pub);
```

**Comment by cescoffier** [comment]
In the future we may want to add: `uncouple`.
