### ISSUE TITLE
Is MessagingProvider that important?

### ISSUE THREAD

**Issue by cescoffier** [eclipse/microprofile-reactive-streams#71]
The `@Incoming` and `@Outgoing` annotations have a `provider` attribute. This provider indicates the _transport_ technology used by the stream. I'm not sure this attribute is relevant as the user code should not care much about it. Typically, if we have something like:

```
@Incoming(topic="hello")
...
```

The implementation can check if there is a stream (Publisher) named `hello` defined in the configuration or somewhere else (`@Produces` annotation - this will be covered by another issue). In the first case, it's the configuration that describes the transport layer (and the rest of the configuration such as the broker url, credentials...).

**Comment by jroper** [comment]
We should definitely allow the messaging provider to be defined in configuration, but in some places I think it would be clearer to have it in code.

On the mailing list there's discussions about CQRS support and having an event log. If you wanted to publish the event log to Kafka (which would be a very common use case), then a method that published the event log would benefit, I think, from indicating that it was the event log that it was publishing in the code, this would make it more clear what that method was doing. Eg:

```java
@Incoming(provider = EventLog.class)
@Outgoing(topic = "foo")
public ProcessorBuilder<EventLogEvent, PublishedEvent> publishEventLog() {
  // ...
}
```
So, `Outgoing` is going to use whatever the default messaging provider is, something that you might want to switch out and not have in code, while incoming uses the event log, something that you would never switch out and so it makes sense to have it in code.

The same applies to integration with CDI events as a messaging provider.

But perhaps we could remove the `provider` value from the first version and require it to always be specified in config, and then see if the use case above for the value makes sense.

**Comment by cescoffier** [comment]
Your use case makes a lot of sense. Now the question, and it's more a CDI related question is: should it be another separated _qualifier_ annotation? like:

```
@Incoming
@IncomingProvider(EventLog.class)
@Outgoing(topic = "foo")
public ProcessorBuilder<EventLogEvent, PublishedEvent> publishEventLog() {
  // ...
}
```

while I'm writing it, I don't really like it. But as a non-CDI expert I don't know if it's more CDI-friendly. @antoinesd what do you think?

**Comment by jroper** [comment]
Closing because I think we've decided to keep the provider attribute as is.
