### ISSUE TITLE
Error handling strategy

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-streams#82]
I've been implementing a lot more tests for the streams TCK, and something has come up.

Should errors be allowed to overtake elements? This turns out to be a very philosophical question, here's some discussion about it from 4 years ago when Akka Streams was being implemented:

https://github.com/akka/akka/issues/15346

See the linked discussion on a commit for even more details.

So, Akka's stance here is that if the stream has an error, it should be propagated ASAP. That means, if there are any buffered elements in front of it, the error should overtake them.  I think the argument for it is generally that, since `onError` can be invoked at any time, regardless of whether there is demand or not, it should not be held up by elements in front of it. That said, `onComplete` can also be invoked at any time regardless of whether there is demand or not, but the same rule doesn't apply to it.

I don't know what RxJava's strategy is.

Here's on example of where this will make a difference:

```java
ReactiveStreams.concat(
  ReactiveStreams.of(1, 2),
  ReactiveStreams.failed(new RuntimeException("failed"))
).recover(t -> 3).toList();
```

If failing fast, then it is technically non deterministic what the resulting list will be - though in practice, it will be just `List(3)`, however, failures are not allowed to overtake elements, then the result will be `List(1, 2, 3)`.

Another possibility for overtaking in the current API exists in `flatMap*` methods, if an error comes from upstream while the current `Publisher`/`CompletionStage`/`Iterable` is still emitting elements, then that error will overtake the elements.

There are a few ways that we can deal with this. One thing about errors overtaking elements is that generally it is non deterministic. So you technically can't require that an implementation always allows errors to overtake elements, you can only say that it's allowed for elements to overtake elements, which effectively gives it the option of allowing it or not. Even if you try to contrive a TCK test to ensure it happens in certain situations, you risk the test relying too much on unspecified implementation details. So I think there are two options:

1. Allow errors to overtake elements
2. Require that errors must never overtake elements

Certainly when implementing number 2 on top of Akka Streams, that's going to be difficult, but I've found even implementing number 2 on the zero dependency implementation makes a lot of very simple stages more complicated than they necessarily need to be.

**Comment by cescoffier** [comment]
RX Java does not overtake elements on errors. I've done a simple test with Reactor and it seems it behaves similarly. 

Now we can allow overtaking elements, but I would rather not make it mandatory.

**Comment by jroper** [comment]
As discussed in the hangout, implementations are allowed to handle errors in a fail fast way, but not required. The spec has already been updated to mention this.
