### ISSUE TITLE
Spec clarification of @Inject @Producer - result same as ServiceLoad?

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-reactive-streams#97]
The spec has support for service loading an engine and for @Injecting an engine in the context
of a container.

Should these always return the same result? 
This has the practical implication that the @Inject's @Producer method needs to use  (a mechanism similar to) ServiceLoader.load to get the engine. 
Thus enabling a users provided Engine, higher in the classpath, to be injected. 
Or should the @Inject always result in the 'default' container - even if the user has provided one that is the 'first' in the list found by the ServiceLoader?

The use case of of an users impl decorating/delegating to the default impl can be me
by the fact that the ServiceLoader mechanism will return a 'set' of matches that can
be iterated.

I would probably vote for @Inject and ServiceLoad returning consistent results -
the interesting thing here is that the spec says what is injected is 'ApplicationScoped'
whereas one would expect what comes back from ServiceLoad to be dependant.
Hmm? 

The spec has:

"If a MicroProfile container provides an implementation of MicroProfile Reactive Streams
Operators, then it must make an application scoped ReactiveStreamsEngine available for injection."

and

"To run this TCK, the container must provide a ReactiveStreamsEngine to be tested as an injectable
ApplicationScoped bean, and the MicroProfile Reactive Streams Operators API must be on the
classpath."

and
in the javadoc...
https://github.com/eclipse/microprofile-reactive-streams/blob/9c88b3fdb6e65c63ca3c40f5609d965c7b3e92f8/api/src/main/java/org/eclipse/microprofile/reactive/streams/spi/ReactiveStreamsEngine.java#L32
The zero argument {@code build} and {@code run} methods on subclasses of this will use
 * the {@link java.util.ServiceLoader} to load an engine for the current context classloader.

**Comment by cescoffier** [comment]
It has been decided to not specify the behavior.

**Comment by cescoffier** [comment]
@hutchig @jroper should we close this issue?

**Comment by cescoffier** [comment]
Closing. Please re-open if needed.
